export interface Profile {
  id: string;
  firstname: string;
  lastname: string;
  age: number;
  country: string;
  city: string;
  maritalStatus: string;
  religiousLevel: string;
  education: string;
  hasBeard?: boolean;
  wearHijab?: boolean;
  wearNiqab?: boolean;
  height: number;
  occupation: string;
  bio: string;
  interests: string[];
  profilePicture?: string;
  isOnline: boolean;
  lastActive: string;
  gender: "male" | "female";
  religiousPractices: string[];
  languagesSpoken: string[];
  familyStatus: string;
  hasChildren: boolean;
  wantsChildren: boolean;
  smokingStatus: string;
  isPrayerRegular: boolean;
  monthlyIncome?: string;
  livingArrangement: string;
  photos: string[];
  verified: boolean;
  joinDate: string;
  profileCompletion: number;
}

export const mockProfiles: Profile[] = [
  {
    id: "1",
    firstname: "أحمد",
    lastname: "محمد",
    age: 28,
    country: "السعودية",
    city: "الرياض",
    maritalStatus: "أعزب",
    religiousLevel: "ملتزم",
    education: "جامعي",
    hasBeard: true,
    height: 175,
    occupation: "مهندس برمجيات",
    bio: "أبحث عن زوجة صالحة تشاركني الحياة وتساعدني على طاعة الله. أحب القراءة والسفر والرياضة.",
    interests: ["القراءة", "السفر", "الرياضة", "التقنية"],
    isOnline: true,
    lastActive: "منذ دقائق",
    gender: "male",
    religiousPractices: ["الصلاة في وقتها", "قراءة القرآن", "صيام النافلة"],
    languagesSpoken: ["العربية", "الإنجليزية"],
    familyStatus: "يعيش مع الأسرة",
    hasChildren: false,
    wantsChildren: true,
    smokingStatus: "لا يدخن",
    isPrayerRegular: true,
    monthlyIncome: "15000-25000 ريال",
    livingArrangement: "مع الأسرة",
    photos: ["/api/placeholder/400/600", "/api/placeholder/400/600"],
    verified: true,
    joinDate: "2024-01-15",
    profileCompletion: 95,
  },
  {
    id: "2",
    firstname: "فاطمة",
    lastname: "علي",
    age: 25,
    country: "الإمارات",
    city: "دبي",
    maritalStatus: "عزباء",
    religiousLevel: "متوسط",
    education: "جامعي",
    wearHijab: true,
    wearNiqab: false,
    height: 160,
    occupation: "معلمة",
    bio: "معلمة متدينة أبحث عن زوج يقدر الدين والأخلاق. أحب التعليم والطبخ والقراءة.",
    interests: ["التعليم", "الطبخ", "القراءة", "الأعمال اليدوية"],
    isOnline: false,
    lastActive: "منذ ساعة",
    gender: "female",
    religiousPractices: ["الحجاب", "الصلاة", "قراءة القرآن"],
    languagesSpoken: ["العربية", "الإنجليزية"],
    familyStatus: "تعيش مع الأسرة",
    hasChildren: false,
    wantsChildren: true,
    smokingStatus: "لا تدخن",
    isPrayerRegular: true,
    monthlyIncome: "8000-12000 درهم",
    livingArrangement: "مع الأسرة",
    photos: ["/api/placeholder/400/600"],
    verified: true,
    joinDate: "2024-02-20",
    profileCompletion: 88,
  },
  {
    id: "3",
    firstname: "محمد",
    lastname: "الأحمد",
    age: 32,
    country: "الكويت",
    city: "الكويت",
    maritalStatus: "مطلق",
    religiousLevel: "ملتزم جداً",
    education: "دراسات عليا",
    hasBeard: true,
    height: 180,
    occupation: "طبيب",
    bio: "طبيب مطلق أبحث عن زوجة مؤمنة لتكوين أسرة مسلمة سعيدة. أحب العمل الخيري والدعوة.",
    interests: ["الطب", "العمل الخيري", "الدعوة", "القراءة"],
    isOnline: true,
    lastActive: "متصل الآن",
    gender: "male",
    religiousPractices: [
      "الصلاة في المسجد",
      "قيام الليل",
      "الدعوة",
      "العمل الخيري",
    ],
    languagesSpoken: ["العربية", "الإنجليزية", "الفرنسية"],
    familyStatus: "يعيش وحده",
    hasChildren: true,
    wantsChildren: true,
    smokingStatus: "لا يدخن",
    isPrayerRegular: true,
    monthlyIncome: "25000+ دينار",
    livingArrangement: "منزل منفصل",
    photos: ["/api/placeholder/400/600", "/api/placeholder/400/600"],
    verified: true,
    joinDate: "2023-12-10",
    profileCompletion: 100,
  },
  {
    id: "4",
    firstname: "عائشة",
    lastname: "حسن",
    age: 23,
    country: "قطر",
    city: "الدوحة",
    maritalStatus: "عزباء",
    religiousLevel: "ملتزم",
    education: "جامعي",
    wearHijab: true,
    wearNiqab: true,
    height: 155,
    occupation: "مصممة جرافيك",
    bio: "مصممة جرافيك محجبة، أحب الفن الإسلامي والتصميم. أبحث عن زوج متدين وطموح.",
    interests: ["التصميم", "الفن الإسلامي", "الخط العربي", "التصوير"],
    isOnline: false,
    lastActive: "منذ يومين",
    gender: "female",
    religiousPractices: ["الحجاب", "النقاب", "الصلاة", "صيام النافلة"],
    languagesSpoken: ["العربية", "الإنجليزية"],
    familyStatus: "تعيش مع الأسرة",
    hasChildren: false,
    wantsChildren: true,
    smokingStatus: "لا تدخن",
    isPrayerRegular: true,
    monthlyIncome: "10000-15000 ريال",
    livingArrangement: "مع الأسرة",
    photos: ["/api/placeholder/400/600"],
    verified: false,
    joinDate: "2024-03-05",
    profileCompletion: 75,
  },
  {
    id: "5",
    firstname: "يوسف",
    lastname: "العتيبي",
    age: 30,
    country: "السعودية",
    city: "جدة",
    maritalStatus: "أعزب",
    religiousLevel: "متوسط",
    education: "جامعي",
    hasBeard: false,
    height: 178,
    occupation: "محاسب",
    bio: "محاسب في شركة كبيرة، أحب السفر والرياضة. أبحث عن شريكة حياة متفاهمة.",
    interests: ["السفر", "كرة القدم", "الأفلام", "الموسيقى"],
    isOnline: true,
    lastActive: "منذ 10 دقائق",
    gender: "male",
    religiousPractices: ["الصلاة", "صيام رمضان"],
    languagesSpoken: ["العربية", "الإنجليزية"],
    familyStatus: "يعيش مع الأسرة",
    hasChildren: false,
    wantsChildren: true,
    smokingStatus: "لا يدخن",
    isPrayerRegular: true,
    monthlyIncome: "12000-18000 ريال",
    livingArrangement: "مع الأسرة",
    photos: ["/api/placeholder/400/600"],
    verified: true,
    joinDate: "2024-01-30",
    profileCompletion: 82,
  },
  {
    id: "6",
    firstname: "مريم",
    lastname: "الشمري",
    age: 27,
    country: "الأردن",
    city: "عمان",
    maritalStatus: "عزباء",
    religiousLevel: "ملتزم",
    education: "دراسات عليا",
    wearHijab: true,
    wearNiqab: false,
    height: 165,
    occupation: "صيدلانية",
    bio: "صيدلانية حاصلة على ماجستير، أحب مساعدة الناس والعمل التطوعي. أبحث عن زوج متدين ومتعلم.",
    interests: ["الطب", "العمل التطوعي", "القراءة", "السباحة"],
    isOnline: false,
    lastActive: "منذ 3 ساعات",
    gender: "female",
    religiousPractices: [
      "الحجاب",
      "الصلاة في وقتها",
      "قراءة القرآن",
      "العمل التطوعي",
    ],
    languagesSpoken: ["العربية", "الإنجليزية", "الفرنسية"],
    familyStatus: "تعيش مع الأسرة",
    hasChildren: false,
    wantsChildren: true,
    smokingStatus: "لا تدخن",
    isPrayerRegular: true,
    monthlyIncome: "800-1200 دينار",
    livingArrangement: "مع الأسرة",
    photos: ["/api/placeholder/400/600", "/api/placeholder/400/600"],
    verified: true,
    joinDate: "2023-11-12",
    profileCompletion: 92,
  },
  {
    id: "7",
    firstname: "عبدالله",
    lastname: "الزهراني",
    age: 35,
    country: "السعودية",
    city: "مكة المكرمة",
    maritalStatus: "أرمل",
    religiousLevel: "ملتزم جداً",
    education: "جامعي",
    hasBeard: true,
    height: 182,
    occupation: "إمام وخطيب",
    bio: "إمام وخطيب مسجد، حافظ للقرآن الكريم. أبحث عن زوجة صالحة تساعدني في تربية أطفالي.",
    interests: ["القرآن الكريم", "الدعوة", "التعليم", "العمل الخيري"],
    isOnline: false,
    lastActive: "منذ يوم",
    gender: "male",
    religiousPractices: [
      "إمامة المسجد",
      "حفظ القرآن",
      "الدعوة",
      "تعليم القرآن",
    ],
    languagesSpoken: ["العربية", "الإنجليزية"],
    familyStatus: "يعيش مع أطفاله",
    hasChildren: true,
    wantsChildren: true,
    smokingStatus: "لا يدخن",
    isPrayerRegular: true,
    monthlyIncome: "8000-12000 ريال",
    livingArrangement: "منزل منفصل",
    photos: ["/api/placeholder/400/600"],
    verified: true,
    joinDate: "2024-02-14",
    profileCompletion: 90,
  },
  {
    id: "8",
    firstname: "خديجة",
    lastname: "المالكي",
    age: 29,
    country: "السعودية",
    city: "المدينة المنورة",
    maritalStatus: "مطلقة",
    religiousLevel: "ملتزم",
    education: "جامعي",
    wearHijab: true,
    wearNiqab: false,
    height: 158,
    occupation: "معلمة قرآن",
    bio: "معلمة قرآن كريم، مطلقة بدون أطفال. أسعى لتكوين أسرة مسلمة تقية ورعة.",
    interests: ["تعليم القرآن", "التجويد", "الخياطة", "الطبخ"],
    isOnline: true,
    lastActive: "متصلة الآن",
    gender: "female",
    religiousPractices: ["تعليم القرآن", "الحجاب", "قيام الليل", "الصيام"],
    languagesSpoken: ["العربية"],
    familyStatus: "تعيش مع الأسرة",
    hasChildren: false,
    wantsChildren: true,
    smokingStatus: "لا تدخن",
    isPrayerRegular: true,
    monthlyIncome: "5000-8000 ريال",
    livingArrangement: "مع الأسرة",
    photos: ["/api/placeholder/400/600"],
    verified: true,
    joinDate: "2023-10-08",
    profileCompletion: 85,
  },
  {
    id: "9",
    firstname: "علي",
    lastname: "الحربي",
    age: 26,
    country: "البحرين",
    city: "المنامة",
    maritalStatus: "أعزب",
    religiousLevel: "متوسط",
    education: "جامعي",
    hasBeard: false,
    height: 174,
    occupation: "مطور ويب",
    bio: "مطور ويب شاب، أحب التكنولوجيا والابتكار. أبحث عن فتاة متعلمة ومتفهمة للعمل في التقنية.",
    interests: ["البرمجة", "الألعاب", "التقنية", "كرة السلة"],
    isOnline: true,
    lastActive: "منذ 5 دقائق",
    gender: "male",
    religiousPractices: ["الصلاة", "صيام رمضان"],
    languagesSpoken: ["العربية", "الإنجليزية"],
    familyStatus: "يعيش مع الأسرة",
    hasChildren: false,
    wantsChildren: true,
    smokingStatus: "لا يدخن",
    isPrayerRegular: true,
    monthlyIncome: "1500-2500 دينار",
    livingArrangement: "مع الأسرة",
    photos: ["/api/placeholder/400/600", "/api/placeholder/400/600"],
    verified: false,
    joinDate: "2024-03-20",
    profileCompletion: 70,
  },
  {
    id: "10",
    firstname: "سارة",
    lastname: "النجار",
    age: 24,
    country: "لبنان",
    city: "بيروت",
    maritalStatus: "عزباء",
    religiousLevel: "ملتزم",
    education: "جامعي",
    wearHijab: true,
    wearNiqab: false,
    height: 162,
    occupation: "مترجمة",
    bio: "مترجمة تجيد عدة لغات، أحب الثقافات المختلفة والأدب. أبحث عن زوج مثقف ومتدين.",
    interests: ["الترجمة", "الأدب", "اللغات", "السفر"],
    isOnline: false,
    lastActive: "منذ 6 ساعات",
    gender: "female",
    religiousPractices: ["الحجاب", "الصلاة", "قراءة القرآن"],
    languagesSpoken: ["العربية", "الإنجليزية", "الفرنسية", "الإسبانية"],
    familyStatus: "تعيش مع الأسرة",
    hasChildren: false,
    wantsChildren: true,
    smokingStatus: "لا تدخن",
    isPrayerRegular: true,
    monthlyIncome: "1000-1500 دولار",
    livingArrangement: "مع الأسرة",
    photos: ["/api/placeholder/400/600"],
    verified: true,
    joinDate: "2024-01-08",
    profileCompletion: 88,
  },
  {
    id: "11",
    firstname: "حسام",
    lastname: "الطيب",
    age: 33,
    country: "مصر",
    city: "القاهرة",
    maritalStatus: "أعزب",
    religiousLevel: "ملتزم",
    education: "دراسات عليا",
    hasBeard: true,
    height: 177,
    occupation: "مدرس جامعي",
    bio: "أستاذ جامعي في كلية الشريعة، أحب البحث والتأليف. أبحث عن زوجة متعلمة ومتدينة.",
    interests: ["البحث العلمي", "التأليف", "القراءة", "الشعر"],
    isOnline: false,
    lastActive: "منذ يوم",
    gender: "male",
    religiousPractices: [
      "التدريس الشرعي",
      "البحث",
      "الصلاة في المسجد",
      "الدعوة",
    ],
    languagesSpoken: ["العربية", "الإنجليزية"],
    familyStatus: "يعيش وحده",
    hasChildren: false,
    wantsChildren: true,
    smokingStatus: "لا يدخن",
    isPrayerRegular: true,
    monthlyIncome: "8000-12000 جنيه",
    livingArrangement: "شقة منفصلة",
    photos: ["/api/placeholder/400/600"],
    verified: true,
    joinDate: "2023-09-15",
    profileCompletion: 95,
  },
  {
    id: "12",
    firstname: "نور",
    lastname: "العبدالله",
    age: 22,
    country: "سوريا",
    city: "دمشق",
    maritalStatus: "عزباء",
    religiousLevel: "متوسط",
    education: "جامعي - طالبة",
    wearHijab: true,
    wearNiqab: false,
    height: 159,
    occupation: "طالبة طب",
    bio: "طالبة طب في السنة الأخيرة، أحب مساعدة المرضى والعمل الإنساني. أبحث عن زوج متفهم ومساند.",
    interests: ["الطب", "المطالعة", "الرسم", "الموسيقى الكلاسيكية"],
    isOnline: true,
    lastActive: "منذ دقيقة",
    gender: "female",
    religiousPractices: ["الحجاب", "الصلاة", "صيام النافلة"],
    languagesSpoken: ["العربية", "الإنجليزية"],
    familyStatus: "تعيش مع الأسرة",
    hasChildren: false,
    wantsChildren: true,
    smokingStatus: "لا تدخن",
    isPrayerRegular: true,
    monthlyIncome: "طالبة",
    livingArrangement: "مع الأسرة",
    photos: ["/api/placeholder/400/600", "/api/placeholder/400/600"],
    verified: false,
    joinDate: "2024-04-01",
    profileCompletion: 65,
  },
  {
    id: "13",
    firstname: "راشد",
    lastname: "المرزوقي",
    age: 31,
    country: "الإمارات",
    city: "أبوظبي",
    maritalStatus: "أعزب",
    religiousLevel: "ملتزم جداً",
    education: "دراسات عليا",
    hasBeard: true,
    height: 183,
    occupation: "مدير تسويق",
    bio: "مدير تسويق في شركة كبيرة، أحب الأعمال والاستثمار. أبحث عن زوجة طموحة ومتدينة.",
    interests: ["الأعمال", "الاستثمار", "القراءة", "الرياضة"],
    isOnline: true,
    lastActive: "متصل الآن",
    gender: "male",
    religiousPractices: [
      "الصلاة في المسجد",
      "قيام الليل",
      "العمل الخيري",
      "الحج والعمرة",
    ],
    languagesSpoken: ["العربية", "الإنجليزية"],
    familyStatus: "يعيش وحده",
    hasChildren: false,
    wantsChildren: true,
    smokingStatus: "لا يدخن",
    isPrayerRegular: true,
    monthlyIncome: "25000+ درهم",
    livingArrangement: "شقة منفصلة",
    photos: ["/api/placeholder/400/600", "/api/placeholder/400/600"],
    verified: true,
    joinDate: "2023-08-22",
    profileCompletion: 100,
  },
  {
    id: "14",
    firstname: "هند",
    lastname: "الأحمد",
    age: 26,
    country: "الكويت",
    city: "الكويت",
    maritalStatus: "عزباء",
    religiousLevel: "ملتزم",
    education: "جامعي",
    wearHijab: true,
    wearNiqab: false,
    height: 163,
    occupation: "محامية",
    bio: "محامية متخصصة في قانون الأسرة، أحب العدالة والدفاع عن الحقوق. أبحث عن زوج عادل ومتفهم.",
    interests: ["القانون", "العدالة الاجتماعية", "القراءة", "السباحة"],
    isOnline: false,
    lastActive: "منذ 4 ساعات",
    gender: "female",
    religiousPractices: ["الحجاب", "الصلاة", "العمل الخيري", "قراءة القرآن"],
    languagesSpoken: ["العربية", "الإنجليزية"],
    familyStatus: "تعيش مع الأسرة",
    hasChildren: false,
    wantsChildren: true,
    smokingStatus: "لا تدخن",
    isPrayerRegular: true,
    monthlyIncome: "2000-3000 دينار",
    livingArrangement: "مع الأسرة",
    photos: ["/api/placeholder/400/600"],
    verified: true,
    joinDate: "2023-12-03",
    profileCompletion: 90,
  },
  {
    id: "15",
    firstname: "عمر",
    lastname: "الشريف",
    age: 29,
    country: "قطر",
    city: "الدوحة",
    maritalStatus: "أعزب",
    religiousLevel: "متوسط",
    education: "جامعي",
    hasBeard: false,
    height: 176,
    occupation: "مهندس مدني",
    bio: "مهندس مدني أعمل في مشاريع كبيرة، أحب البناء والتشييد. أبحث عن زوجة داعمة ومتفائلة.",
    interests: ["الهندسة", "البناء", "السيارات", "كرة القدم"],
    isOnline: true,
    lastActive: "منذ 30 دقيقة",
    gender: "male",
    religiousPractices: ["الصلاة", "صيام رمضان", "الزكاة"],
    languagesSpoken: ["العربية", "الإنجليزية"],
    familyStatus: "يعيش مع الأسرة",
    hasChildren: false,
    wantsChildren: true,
    smokingStatus: "لا يدخن",
    isPrayerRegular: true,
    monthlyIncome: "20000-30000 ريال",
    livingArrangement: "مع الأسرة",
    photos: ["/api/placeholder/400/600"],
    verified: true,
    joinDate: "2024-02-28",
    profileCompletion: 80,
  },
];

// Mock current user
export const mockCurrentUser: Profile = {
  id: "current",
  firstname: "محمد",
  lastname: "أحمد",
  age: 27,
  country: "السعودية",
  city: "الرياض",
  maritalStatus: "أعزب",
  religiousLevel: "ملتزم",
  education: "جامعي",
  hasBeard: true,
  height: 175,
  occupation: "مبرمج",
  bio: "مبرمج شاب أبحث عن زوجة صالحة",
  interests: ["البرمجة", "القراءة", "الرياضة"],
  isOnline: true,
  lastActive: "متصل الآن",
  gender: "male",
  religiousPractices: ["الصلاة", "قراءة القرآن"],
  languagesSpoken: ["العربية", "الإنجليزية"],
  familyStatus: "يعيش مع الأسرة",
  hasChildren: false,
  wantsChildren: true,
  smokingStatus: "لا يدخن",
  isPrayerRegular: true,
  monthlyIncome: "10000-15000 ريال",
  livingArrangement: "مع الأسرة",
  photos: ["/api/placeholder/400/600"],
  verified: true,
  joinDate: "2024-01-01",
  profileCompletion: 85,
};

// Filter options matching the API structure
export const filterOptions = {
  countries: [
    "السعودية",
    "الإمارات",
    "الكويت",
    "قطر",
    "البحرين",
    "الأردن",
    "لبنان",
    "مصر",
    "سوريا",
  ],
  cities: {
    السعودية: ["الرياض", "جدة", "مكة المكرمة", "المدينة المنورة", "الدمام"],
    الإمارات: ["دبي", "أبوظبي", "الشارقة", "عجمان"],
    الكويت: ["الكويت", "الأحمدي", "الفروانية"],
    قطر: ["الدوحة", "الوكرة", "الريان"],
    البحرين: ["المنامة", "المحرق", "الرفاع"],
    الأردن: ["عمان", "إربد", "الزرقاء"],
    لبنان: ["بيروت", "طرابلس", "صيدا"],
    مصر: ["القاهرة", "الإسكندرية", "الجيزة"],
    سوريا: ["دمشق", "حلب", "حمص"],
  },
  // Frontend displays Arabic, backend expects English (see lib/constants/filter-mapping.ts)
  maritalStatuses: ["أعزب", "عزباء", "مطلق", "مطلقة", "أرمل", "أرملة"],
  religiousLevels: ["أساسي", "متوسط", "ملتزم", "ملتزم جداً"],
  educationLevels: ["ابتدائي", "ثانوي", "ثانوي عام", "دبلوم", "جامعي", "بكالوريوس", "دراسات عليا", "ماجستير", "دكتوراه", "أخرى"],
  occupations: [
    "مهندس",
    "طبيب",
    "معلم",
    "محاسب",
    "محام",
    "مبرمج",
    "مدير",
    "صيدلاني",
    "مترجم",
    "طالب",
  ],
};
