const fs = require('fs');
const path = require('path');

// Function to load .env.local manually if not in process.env
function loadEnv() {
  const envPath = path.resolve(process.cwd(), '.env.local');
  if (fs.existsSync(envPath)) {
    console.log('Loading environment from .env.local');
    const content = fs.readFileSync(envPath, 'utf8');
    content.split('\n').forEach(line => {
      const match = line.match(/^([^=]+)=(.*)$/);
      if (match) {
        const key = match[1].trim();
        const value = match[2].trim().replace(/^['"]|['"]$/g, ''); // Remove quotes
        if (!process.env[key]) {
          process.env[key] = value;
        }
      }
    });
  } else {
    // Check parent directory for .env.local (monorepo/root style)
    const rootEnvPath = path.resolve(process.cwd(), '../.env.local');
    if (fs.existsSync(rootEnvPath)) {
        console.log('Loading environment from ../.env.local');
        const content = fs.readFileSync(rootEnvPath, 'utf8');
        content.split('\n').forEach(line => {
            const match = line.match(/^([^=]+)=(.*)$/);
            if (match) {
              const key = match[1].trim();
              const value = match[2].trim().replace(/^['"]|['"]$/g, '');
              if (!process.env[key]) {
                process.env[key] = value;
              }
            }
          });
    }
  }
}

// Load env vars
loadEnv();

const swSourcePath = path.join(process.cwd(), 'public', 'firebase-messaging-sw.js');
// We don't want to overwrite the source if it's the template, 
// strictly speaking we should have a template file and a generated file.
// But to keep it simple and per the plan, we will read the current one, 
// check if it needs injection, and overwrite it. 
// OR better: Create a template backup if not exists.

const swTemplatePath = path.join(process.cwd(), 'public', 'firebase-messaging-sw.template.js');

if (!fs.existsSync(swTemplatePath)) {
    // If no template exists yet, assume current SW is the source/template
    // OR create a fresh template if the current one is broken/empty.
    // Let's assume the current one is the template logic minus the init code.
    // Creating a copy to serve as template
    if (fs.existsSync(swSourcePath)) {
        fs.copyFileSync(swSourcePath, swTemplatePath);
        console.log('Created template from existing service worker.');
    } else {
        console.error('No service worker file found to use as template!');
        process.exit(1);
    }
}

// Read the template
let swContent = fs.readFileSync(swTemplatePath, 'utf8');

// Configuration values
const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

// Check if we have minimal config
if (!firebaseConfig.apiKey || !firebaseConfig.projectId) {
    console.warn('Warning: Missing Firebase configuration in environment variables. Service Worker might not work.');
}

// The initialization snippet
const initSnippet = `
// Initialize Firebase
// This section is auto-generated by scripts/generate-sw.js
if (firebase.apps.length === 0) {
  firebase.initializeApp(${JSON.stringify(firebaseConfig, null, 2)});
}
`;

// Inject the snippet
// We place it after the scripts import
if (swContent.includes('importScripts')) {
    // Find the last importScripts line
    const lastImportIndex = swContent.lastIndexOf('importScripts');
    const endOfLineIndex = swContent.indexOf(';', lastImportIndex);
    
    if (endOfLineIndex !== -1) {
        // Insert after the last import
        const before = swContent.slice(0, endOfLineIndex + 1);
        const after = swContent.slice(endOfLineIndex + 1);
        swContent = before + '\n' + initSnippet + after;
    } else {
        // Fallback: Prepend
        swContent = initSnippet + '\n' + swContent; 
    }
} else {
    // No imports? strange, but append init at top
    swContent = initSnippet + '\n' + swContent;
}

// Write the generated file
fs.writeFileSync(swSourcePath, swContent);
console.log('Generated public/firebase-messaging-sw.js with Firebase configuration.');
